<a href="https://colab.research.google.com/github/wafa-b/Intro-to-TensorFlow-for-Deep-Learning/blob/master/Introduction_to_Colab_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Introduction to Colab and Python**


Colab is a Python development environment that runs in the browser using Google Cloud.

For example, to print "Hello World", just hover the mouse over [ ] and press the play button to the upper left. Or press shift-enter to execute.

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

In [1]:
print('Hello World')

Hello World


## Functions, Conditionals, and Iteration


Create a Python function, and call it from a loop.

In [9]:
def HelloWorldXY(X,Y):
  if (X < 10):
    print('Hello World , X was < 10')
  elif (X < 20):
    print('Hello Wolrd, X was >= 10 but < 20')
  else:
    print('Hello World X was >= 20')
  return X + Y

for i in range(8,25,5): # i=8, 13, 18, 23 (start, stop, step)
  print('--- Now running with i: {}'.format(i))
  r=HelloWorldXY(i,i)
  print('--- Result from HelloWorld: {}'.format(r))

--- Now running with i: 8
Hello World , X was < 10
--- Result from HelloWorld: 16
--- Now running with i: 13
Hello Wolrd, X was >= 10 but < 20
--- Result from HelloWorld: 26
--- Now running with i: 18
Hello Wolrd, X was >= 10 but < 20
--- Result from HelloWorld: 36
--- Now running with i: 23
Hello World X was >= 20
--- Result from HelloWorld: 46


In [10]:
print(HelloWorldXY(1,2))

Hello World , X was < 10
3


A loop starting at 0 to 2 (exclusive),We could do any of the following:

In [11]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
  print(i)
print("Iterate over an actual list.")
for i in[0,1]:
  print(i)
print("While works")
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


In [12]:
print("Python supports standard key words like continue and break")
while True:
  print('Entered while')
  break

Python supports standard key words like continue and break
Entered while


## Numpy and lists
Python has lists built into the language.
However, we will use a library called numpy for this.
Numpy gives us lots of support functions that are useful when doing Machine Learning.

Here, we will also see an import statement. This statement makes the entire numpy package available and we can access those symbols using the abbreviated 'np' syntax.

In [1]:
import numpy as np # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(['Hello','World'])
a = np.append(a,'!')
print('Curreny\t array: {}'.format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print('Index: {}, Element: {}'.format(i,e)) 

Curreny	 array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, Element: Hello
Index: 1, Element: World
Index: 2, Element: !


In [2]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print('Max: {}'.format(np.max(b)))
print('Average: {}'.format(np.average(b)))
print('Max Index: {}'.format(np.argmax))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max Index: <function argmax at 0x7f8e58584378>


In [3]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b),format(type(0))))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'int'>


In [5]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3,3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.36444869 0.9087753  0.84557755]
 [0.76685993 0.63385268 0.14618063]
 [0.15818064 0.19216633 0.84226337]]


In [6]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


## Colab Specifics

Colab is a virtual machine you can access directly. To run commands at the VM's terminal, prefix the line with an exclamation point (!).



In [7]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd


Doing $ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Feb  5 18:37 sample_data
/content


In [8]:
print("Install numpy")  # Just for test, numpy is actually preinstalled in all Colab instances
!pip install numpy

Install numpy


**Exercise**

Create a code cell underneath this text cell and add code to:


*   List the path of the current directory (pwd)
* Go to / (cd) and list the content (ls -l)

In [9]:
!pwd
!cd /
!ls -l

/content
total 4
drwxr-xr-x 1 root root 4096 Feb  5 18:37 sample_data


All usage of Colab in this course is completely free or charge. Even GPU usage is provided free of charge for some hours of usage every day.

**Using GPUs**
* Many of the exercises in the course executes more quickly by using GPU runtime: Runtime | Change runtime type | Hardware accelerator | GPU

**Some final words on Colab**
*   You execute each cell in order, you can edit & re-execute cells if you want
*   Sometimes, this could have unintended consequences. For example, if you add a dimension to an array and execute the cell multiple times, then the cells after may not work. If you encounter problem reset your environment:
  *   Runtime -> Restart runtime... Resets your Python shell
  *   Runtime -> Restart all runtimes... Will reset the Colab image, and get you back to a 100% clean environment
* You can also clear the output in the Colab by doing: Edit -> Clear all outputs
* Colabs in this course are loaded from GitHub. Save to your Google Drive if you want a copy with your code/output: File -> Save a copy in Drive...

**Learn More**
*   Check out [this](https://www.youtube.com/watch?v=inN8seMm7UI&list=PLQY2H8rRoyvwLbzbnKJ59NkZvQAW9wLbx&index=3) episode of #CodingTensorFlow.
